spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelreservation
    username: hotelreservation
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
  docker:
    compose:
      file: src/docker/compose.yml
      enabled: true
      lifecycle-management: start_only
stripe:
  api:
    key: sk_test_51OgSUzCvwqwJehZs1ykmgRGJuhcNGh3SZ60JA5LIbO2053kyQsGxFAk308ADHEKeznRi4irGbgfhZY1vQr5TkOcS00FpGEut61